import os

import openai

# Retrieve the API key from an environment variable

api_key = os.environ.get('OPENAI_API_KEY')

# Set up the OpenAI API key

openai.api_key = api_key

# Define a function to check if the text is likely to be AI-generated

def is_ai_text(text):

    # Use OpenAI API to classify the text

    response = openai.Completion.create(

        engine='text-davinci-003',

        prompt=text,

        max_tokens=1,

        n=1,

        stop=None,

        temperature=0

    )

    

    # Get the classification label

    label = response.choices[0].text.strip()

    

    # Check if the label suggests AI-generated text

    if label == 'AI-generated':

        return True

    

    # Otherwise, assume it's not AI-generated

    return False

# Example usage

text1 = "This is a sample email written by a human."

text2 = "Dear customer, we are pleased to inform you that your request has been processed. This text was generated by AI."

text3 = "The quick brown fox jumps over the lazy dog."

print(is_ai_text(text1))  # False

print(is_ai_text(text2))  # True

print(is_ai_text(text3))  # False

 

